---
  backend_secret: "0e616dc02e3b538e077454ff93e4eca6" # ключ для админки
  manifest_url: "http://109.202.17.170/detective_beta/static/main.json" # адрес манифеста
  cheat: false # разрешить читерить
  fake_validation: true
  logger:
    separate_users: true
    console_silent: true
    console_level: "info"
    file_silent: false
    file_level: "silly"
    file_name: "logs/server.##.log"
    filter_params: # параметры которые будут отображаться в логе в виде sessoin=Filtered
      sq_session_id: true
      auth_key: true
      sess_id: true
      gamedata: true
  networks: #настройки социальных сетей
    5:
      name: "hybrid"
      secret_key: "tebyzenkuycgfzkudrtyuisgh"
      accounts:
        DEV:
          secret: "lGj6RhuiI9Z76CrE51hq"
        LC:
          secret: "lGj6RhuiI9Z76CrE51hq"
        GC:
          secret: "lGj6RhuiI9Z76CrE51hq"
        FB:
          url: "https://graph.facebook.com/me?access_token=<%= key %>"
        VK:
          url: "https://api.vk.com/method/getUserSettings?uid=<%= id %>&access_token=<%= key %>"
      local: "DEV"
      verify_url: "https://sandbox.itunes.apple.com/verifyReceipt"
