---
  port: 3000
  cdn_root_url: "http://mb.static.socialquantum.ru/cdn/hog/" # адрес до cdn
  cdn_cache_dir: "./tmp/node_cdn_cache/" # директория для кэша cdn
  static_dir: "../static/" # директория со статикой проекта
  manifest_main: "../static/main.json" # локальный путь до главного манифеста cdn
  template_dir: "./static/" # директория с шаблонами iframe
  admin_dir: "/../static/_bin/admin_users/" # директория с админским js
  root_dir: "/../" # корень проекта
  world_migrations_dir: "./world_migrations" # директория с миграциями для мира пользователя
  world_migrations_scripts_dir: "./world_migrations/scripts" # директория для скриптинга в миграциях
  share_url: "http://127.0.0.1:3000/share" # адрес для постинга на стену
  assets_url: "http://127.0.0.1:3000/cdn/" # адрес для ассетов (в данном случае через cdn)
  process_url: "http://127.0.0.1:3000/process" # адрес для процессинга
  products: "./tmp/products.json"
  cheat: false # разрешить читерить
  fake_validation: false
  logger:
    separate_users: true
    console_silent: false
    console_level: "info"
    file_silent: false
    file_level: "silly"
    file_name: "logs/server.##.log"
    filter_params: # параметры которые будут отображаться в логе в виде sessoin=Filtered
      sq_session_id: true
      auth_key: true
      sess_id: true
      gamedata: true
  #настройки для скриптинга(для миграций меняется base_js_dir)
  batch_runner:
    base_js_dir: "tmp/"
    custom_js_dir: "tmp/custom/" # директория для
    inactive_timeout: 40
    check_interval: 10 #Частота проверки загруженых версий бачраннера в секундах
  push_notifier:
    ios:
      type: "ApplePushWorker"
      app_name: "detective"
  networks: #настройки социальных сетей
    5:
      name: "hybrid"
      secret_key: "tebyzenkuycgfzkudrtyuisgh"
      accounts:
        DEV:
          secret: "lGj6RhuiI9Z76CrE51hq"
        LC:
          secret: "lGj6RhuiI9Z76CrE51hq"
        GC:
          secret: "lGj6RhuiI9Z76CrE51hq"
        FB:
          url: "https://graph.facebook.com/me?access_token=<%= key %>"
        VK:
          url: "https://api.vk.com/method/getUserSettings?uid=<%= id %>&access_token=<%= key %>"
      local: "DEV"
      verify_url: "https://sandbox.itunes.apple.com/verifyReceipt"
