var helper = require('./../helper');
eval(helper.initContextCode());

describe('case_03', function() {
    it('should be playable', function() {
        helper.setContextWorld(context, {
            "player": {
                "exp": 0,
                "level": 1,
                "game_balance": 3000,
                "real_balance": 100,
                "energy": {
                    "current": 100,
                    "increment_time": 1001000
                },
                "gender": "male",
                "boosters": {}
            },
            "options": {
                "random_seed": 22,
                "init_time": 1000000,
                "last_command_time": Date.now()
            },
            "immediate_data": {
                "analyzed_items": {},
                "triggers": {}
            },
            "partners": {},
            "unlocked_cases": ["case_03"],
            "open_cases": {}
        });

        // Hack to make tests smaller, faster and cleaner
        helper.sandbox.stub(context.hog, "sceneMaxScore", function() {
            return 1000000000;
        });

        Executor.run("open_case", {"case": "case_03"});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_1", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_1", "time": 1010000, "scores": 1000000000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "bonus_1", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "bonus_1", "time": 1010000, "scores": 1000000000});
        Executor.run("click_lab_item", {"lab_item": "body", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "body", "time": 222620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "screws", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "screws", "time": 22620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "jessica", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_2", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_2", "time": 1010000, "scores": 1000000000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "briefcase", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "phone_number", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "phone_number", "time": 22620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "greenroad", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_4", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_4", "time": 1010000, "scores": 1000000000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "laptop", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "laptop", "time": 22620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "keyboard", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "fingerprints", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "fingerprints", "time": 22620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "greenroad", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "camera_recording", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "camera_recording", "time": 52620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "jessica", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "contract", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "contract", "time": 22620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_task", {"index": 0});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "miranda", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_5", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_5", "time": 1010000, "scores": 1000000000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "torn_photo", "time": 2250000});
        Executor.run("end_minigame", {"energy": 9, "time": 2300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "porno_back", "time": 3300000});
        Executor.run("end_minigame", {"energy": 9, "time": 3400000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "realtor", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_6", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_6", "time": 1010000, "scores": 1000000000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "pool_contract", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_task", {"index": 1});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "jack_white", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_1", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_1", "time": 1010000, "scores": 900000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "pool_filter", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_5", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_5", "time": 1010000, "scores": 900000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "mirandas_dress", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "miranda", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "disk_special", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "disk_special", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "bonus_3", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "bonus_3", "time": 1010000, "scores": 725000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "insurance_number", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "insurance_number", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_task", {"index": 0});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_3", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_3", "time": 1010000, "scores": 1000000000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "bedclothes", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "bedclothes", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "jessica", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "jack_white", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_3", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_3", "time": 1010000, "scores": 760000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "swimsuit", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "swimsuit", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_2", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_2", "time": 1010000, "scores": 760000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "safe", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "safe", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "diving_photo", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_1", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_1", "time": 1010000, "scores": 760000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "tree_leaves", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "contact_lens", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "contact_lens", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "jessica", "time": 66845000});

        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_task", {"index": 0});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "additional_laptop", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "additional_laptop", "time": 82620000});

        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "livingroom_photo", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});

        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "opis", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_scene", {"scene": "scene_6", "time": 1002000, "boosters": [], "hints": 1});
        Executor.run("end_scene", {"scene": "scene_6", "time": 1010000, "scores": 1000000000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("start_minigame", {"forensic_item": "shredded_doc", "time": 1250000});
        Executor.run("end_minigame", {"energy": 9, "time": 1300000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "houses_for_sale", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "houses_for_sale", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "greenroad", "time": 66845000});

        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "case_code", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "case_code", "time": 82620000});

        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_task", {"index": 0});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_lab_item", {"lab_item": "phone_number_2", "time": 1020000});
        Executor.run("click_lab_item", {"lab_item": "phone_number_2", "time": 82620000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "realtor", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("click_suspect", {"suspect": "realtor", "time": 66845000});
        Executor.run("execute_next_trigger");
        Executor.run("click_task", {"index": 0});
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        Executor.run("execute_next_trigger");
        //console.log(JSON.stringify(context.storage.getDump(), null, 4));
    });
});